# Generated by Django 5.2.12 on 2026-04-07 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_brand_category_model_modelyear_engine_part'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='parts/%Y/%m/%d/')),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='marketplace.part')),
            ],
            options={
                'verbose_name': 'Part Image',
                'verbose_name_plural': 'Part Images',
                'db_table': 'part_images',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
    ]
