# Generated by Django 5.2.12 on 2026-04-10 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_cart_order_orderitem_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.brand')),
                ('engine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.engine')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.model')),
                ('model_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.modelyear')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Vehicle',
                'verbose_name_plural': 'User Vehicles',
                'db_table': 'user_vehicles',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
