# Generated by Django 5.2.12 on 2026-04-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_uservehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='supplier_notes',
            field=models.TextField(blank=True, help_text='Notes from supplier when approving/rejecting order', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUPPLIER_PENDING', 'Supplier Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PAID', 'Paid'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='SUPPLIER_PENDING', max_length=20),
        ),
    ]
